version: '3.8'

volumes:
  prometheus_data: {}
  grafana-storage: {}

services:
  server:
    build: .
    image: server:test2
    ports:
      - "8085:8085"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: "no"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_conf/datasource/default.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana_conf/dashboard/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana_conf/dashboard/http4s_example_server_dashboard.json:/etc/grafana/provisioning/dashboards/http4s_example_server_dashboard.json
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: "no"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
        
