{
 "title": "http4s Sample Dashboard",
 "description": "Simple sample dashboard for some of the default metrics exported by the http4s-prometheus-metrics",
 "tags": [
  "JVM",
  "prometheus",
  "http4s"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "http4s Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests by Http Method and Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "user_server_request_count_total"
    }
   ]
  },
  { "title": "Server Active Requests", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 } },
  { "title": "Response Duration (seconds)", "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 } },
  { "title": "Jvm Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}} memory [{{instance}}]" }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current [{{instance}}]" },
    { "expr": "jvm_threads_daemon", "legendFormat": "daemon [{{instance}}]" }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "loaded [{{instance}}]" }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  }
 ]
}